[error] sbt.librarymanagement.ResolveException: Error downloading org.scalanlp:breeze-viz_2.11:1.1
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\hawki\.ivy2\localorg.scalanlp\breeze-viz_2.11\1.1\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalanlp/breeze-viz_2.11/1.1/breeze-viz_2.11-1.1.pom
[error] Error downloading org.scalanlp:breeze_2.11:1.1
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\hawki\.ivy2\localorg.scalanlp\breeze_2.11\1.1\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalanlp/breeze_2.11/1.1/breeze_2.11-1.1.pom
[error] Error downloading org.apache.spark:spark-core_2.11:3.0.0
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\hawki\.ivy2\localorg.apache.spark\spark-core_2.11\3.0.0\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/apache/spark/spark-core_2.11/3.0.0/spark-core_2.11-3.0.0.pom
[error] Error downloading org.apache.spark:spark-sql_2.11:3.0.0
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\hawki\.ivy2\localorg.apache.spark\spark-sql_2.11\3.0.0\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/apache/spark/spark-sql_2.11/3.0.0/spark-sql_2.11-3.0.0.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error] 	at lmcoursier.CoursierDependencyResolution$$Lambda$3796/0x0000000000000000.apply(Unknown Source)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$2960/0x0000000000000000.apply(Unknown Source)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.util.Tracked$$$Lambda$2740/0x0000000000000000.apply(Unknown Source)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$2853/0x0000000000000000.apply(Unknown Source)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$2956/0x0000000000000000.apply(Unknown Source)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.util.Tracked$$$Lambda$2636/0x0000000000000000.apply(Unknown Source)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3678)
[error] 	at sbt.Classpaths$$$Lambda$599/0x0000000000000000.apply(Unknown Source)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at scala.Function1$$Lambda$235/0x0000000000000000.apply(Unknown Source)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.internal.util.$tilde$greater$$Lambda$2495/0x0000000000000000.apply(Unknown Source)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.Execute$$Lambda$2521/0x0000000000000000.apply(Unknown Source)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.Execute$$Lambda$2505/0x0000000000000000.apply(Unknown Source)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$2518/0x0000000000000000.apply(Unknown Source)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:823)
[error] (ssExtractDependencies) sbt.librarymanagement.ResolveException: Error downloading org.scalanlp:breeze-viz_2.11:1.1
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\hawki\.ivy2\localorg.scalanlp\breeze-viz_2.11\1.1\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalanlp/breeze-viz_2.11/1.1/breeze-viz_2.11-1.1.pom
[error] Error downloading org.scalanlp:breeze_2.11:1.1
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\hawki\.ivy2\localorg.scalanlp\breeze_2.11\1.1\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalanlp/breeze_2.11/1.1/breeze_2.11-1.1.pom
[error] Error downloading org.apache.spark:spark-core_2.11:3.0.0
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\hawki\.ivy2\localorg.apache.spark\spark-core_2.11\3.0.0\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/apache/spark/spark-core_2.11/3.0.0/spark-core_2.11-3.0.0.pom
[error] Error downloading org.apache.spark:spark-sql_2.11:3.0.0
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\hawki\.ivy2\localorg.apache.spark\spark-sql_2.11\3.0.0\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/apache/spark/spark-sql_2.11/3.0.0/spark-sql_2.11-3.0.0.pom
